{{- if and .Values.rbac.create .Values.rbac.rules }}
kind: {{ include "service.rbac.get.kind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "service.rbac.get.kind" . }}Binding
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "service.rbac.get.kind" . }}
  name: {{ include "service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
