{{- if .Values.secretproviderclass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "service.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.secretproviderclass.name }}
          objectType: "secretsmanager"
{{- end }}