{{- $root := . -}}
{{- if .Values.hooks.enabled -}}
{{- range $index, $hook := .Values.hooks.jobs }}
{{- if $hook.enabled }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $root.Release.Name }}-{{ $hook.name }}-rb"
  namespace: {{ $root.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ $root.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
    app.kubernetes.io/version: {{ $root.Values.image.tag | quote }}
    helm.sh/chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the job is considered part of the release.
    "helm.sh/hook": {{ default $hook.type "pre-install" | quote }}
    "helm.sh/hook-weight": "-{{ add1 $index }}"
    "helm.sh/hook-delete-policy": {{ default $hook.deletePolicy "before-hook-creation, hook-succeeded" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $root.Release.Name }}-{{ $hook.name }}-role"
subjects:
  - kind: ServiceAccount
    name: {{ $hook.serviceAccount.name | default (printf "%s-%s-sa" $root.Release.Name $hook.name) }}
    namespace: {{ $root.Release.Namespace | quote }}

{{- end -}}
{{- end -}}
{{- end -}}