name: Deploy Infrastructure

on:
  push:
    paths:
      - terraform/**
    branches:
      - main

permissions:
  id-token: write
  contents: read

env: 
  ROLE_TO_ASSUME: arn:aws:iam::123456789:role/actions
  AWS_REGION: ap-northeast-3

jobs:
  terraform:
    strategy:
      matrix:
        module: [core, k8s]
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-session-name: tempsession
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: terraform/${{ matrix.module }}
      run: terraform init -backend-config=envs/development/backend.hcl -reconfigure

    - name: Terraform Validate
      working-directory: terraform/${{ matrix.module }}
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform/${{ matrix.module }}
      run: terraform plan -var-file=envs/development/terraform.tfvars -out=tfplan

    - name: Terraform Apply
      working-directory: terraform/${{ matrix.module }}
      run: terraform apply -auto-approve tfplan